version: '3.8'
services:
  api:
    build:
      context: ./src/
      target: dev
    restart: always
    volumes:
      - ./src/:/src
    command: npm run start:dev
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME_FILE: /run/secrets/db_username
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_username
      - db_password
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - ./postgres/initdb.d/:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_username
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: ${DB_NAME}
    secrets:
      - db_username
      - db_password

secrets:
  db_username:
    file: ./postgres/secrets/username.txt
  db_password:
    file: ./postgres/secrets/password.txt
    
volumes:
  pgdata: {}
