version: '3.8'
services:
  api:
    build: 
      context: ./src/
      target: dev
    volumes:
      - ./src/:/src
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*